x-openedx-service:
  &openedx-service
  image: 466538543953.dkr.ecr.eu-central-1.amazonaws.com/phd-experiment-6888bd00add5eb8ac6bb3199:teak-demo-dev
  stdin_open: true
  tty: true
  volumes:
    # theme files
    - ../build/openedx/themes:/openedx/themes

services:
  permissions:
    environment:
      OPENEDX_USER_ID: "1001"

  lms:
    <<: *openedx-service
    command: ./manage.py lms runserver 0.0.0.0:8000
    environment:
        DJANGO_SETTINGS_MODULE: lms.envs.tutor.development
    ports:
        - "8000:8000"
    networks:
      default:
        aliases:
          - "www.myopenedx.com"

  cms:
    <<: *openedx-service
    command: ./manage.py cms runserver 0.0.0.0:8000
    environment:
        DJANGO_SETTINGS_MODULE: cms.envs.tutor.development
    ports:
        - "8001:8000"

  meilisearch:
    ports:
      - "127.0.0.1:7700:7700"
    networks:
      default:
        aliases:
          - "meilisearch.www.myopenedx.com"

  # Additional service for watching theme changes
  watchthemes:
    <<: *openedx-service
    command: npm run watch-sass
    restart: unless-stopped

  
  superset:
    image: edunext/aspects-superset:2.3.1
    user: root
    volumes:
      - ../../env/plugins/aspects/apps/superset/docker:/app/docker
      - ../../env/plugins/aspects/apps/superset/pythonpath:/app/pythonpath
      - ../../env/plugins/aspects/apps/superset/security:/app/security
      - ../../env/plugins/aspects/apps/superset/superset_home:/app/superset_home
      - ../../env/plugins/aspects/apps/superset/scripts:/app/scripts
      - ../../env/plugins/aspects/build/aspects-superset/openedx-assets:/app/openedx-assets        
    restart: unless-stopped
    environment:
      DATABASE_DIALECT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_DB: superset
      DATABASE_PASSWORD: 83VDXRV5RAQJ7bk4Sg41Mz7q
      DATABASE_USER: superset
      OAUTH2_CLIENT_SECRET: 4FYoh0RsE3PA9qvT
      SECRET_KEY: 6UDIsoIHFGwIqonQsp6Bl5ZC
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 
      SUPERSET_HOST: superset.www.myopenedx.com
      SUPERSET_PORT: 8088
      OAUTH2_ACCESS_TOKEN_PATH: "/oauth2/access_token/"
      OAUTH2_AUTHORIZE_PATH: "/oauth2/authorize/"
      OPENEDX_LMS_ROOT_URL: "http://www.myopenedx.com:8000"
      OAUTH2_CLIENT_ID: JNdZZWZF4alnbwUY
      SUPERSET_ENV: development
    command: ["bash", "/app/docker/docker-bootstrap.sh", "app"]
    ports:
      - 8088:8088
    depends_on:
      - mysql
      - redis
      - superset-worker
      - superset-worker-beat

  superset-worker:
    image: edunext/aspects-superset:2.3.1
    user: root
    volumes:
      - ../../env/plugins/aspects/apps/superset/docker:/app/docker
      - ../../env/plugins/aspects/apps/superset/pythonpath:/app/pythonpath
      - ../../env/plugins/aspects/apps/superset/security:/app/security
      - ../../env/plugins/aspects/apps/superset/superset_home:/app/superset_home
      - ../../env/plugins/aspects/apps/superset/scripts:/app/scripts
      - ../../env/plugins/aspects/build/aspects-superset/openedx-assets:/app/openedx-assets        
    restart: unless-stopped
    environment:
      DATABASE_DIALECT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_DB: superset
      DATABASE_PASSWORD: 83VDXRV5RAQJ7bk4Sg41Mz7q
      DATABASE_USER: superset
      OAUTH2_CLIENT_SECRET: 4FYoh0RsE3PA9qvT
      SECRET_KEY: 6UDIsoIHFGwIqonQsp6Bl5ZC
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 
      SUPERSET_HOST: superset.www.myopenedx.com
      SUPERSET_PORT: 8088
      OAUTH2_ACCESS_TOKEN_PATH: "/oauth2/access_token/"
      OAUTH2_AUTHORIZE_PATH: "/oauth2/authorize/"
      OPENEDX_LMS_ROOT_URL: "http://www.myopenedx.com:8000"
      OAUTH2_CLIENT_ID: JNdZZWZF4alnbwUY
      SUPERSET_ENV: development
    command: ["bash", "/app/docker/docker-bootstrap.sh", "worker"]
    healthcheck:
      test: ["CMD-SHELL", "celery inspect ping -A superset.tasks.celery_app:app -d celery@$$HOSTNAME"]
    depends_on:
      - mysql
      - redis

  superset-worker-beat:
    image: edunext/aspects-superset:2.3.1
    user: root
    volumes:
      - ../../env/plugins/aspects/apps/superset/docker:/app/docker
      - ../../env/plugins/aspects/apps/superset/pythonpath:/app/pythonpath
      - ../../env/plugins/aspects/apps/superset/security:/app/security
      - ../../env/plugins/aspects/apps/superset/superset_home:/app/superset_home
      - ../../env/plugins/aspects/apps/superset/scripts:/app/scripts
      - ../../env/plugins/aspects/build/aspects-superset/openedx-assets:/app/openedx-assets        
    restart: unless-stopped
    environment:
      DATABASE_DIALECT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_DB: superset
      DATABASE_PASSWORD: 83VDXRV5RAQJ7bk4Sg41Mz7q
      DATABASE_USER: superset
      OAUTH2_CLIENT_SECRET: 4FYoh0RsE3PA9qvT
      SECRET_KEY: 6UDIsoIHFGwIqonQsp6Bl5ZC
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 
      SUPERSET_HOST: superset.www.myopenedx.com
      SUPERSET_PORT: 8088
      OAUTH2_ACCESS_TOKEN_PATH: "/oauth2/access_token/"
      OAUTH2_AUTHORIZE_PATH: "/oauth2/authorize/"
      OPENEDX_LMS_ROOT_URL: "http://www.myopenedx.com:8000"
      OAUTH2_CLIENT_ID: JNdZZWZF4alnbwUY
      SUPERSET_ENV: development
    command: ["bash", "/app/docker/docker-bootstrap.sh", "beat"]
    healthcheck:
      disable: true
    depends_on:
      - mysql
      - redis



  clickhouse:
      volumes:
          - ../../data/clickhouse:/var/lib/clickhouse/
          - ../../env/plugins/aspects/apps/clickhouse/dev_config:/etc/clickhouse-server/config.d/
          - ../../env/plugins/aspects/apps/clickhouse/users:/etc/clickhouse-server/users.d/







  mfe:
     ports:
         - 1999:8002 # authn
         - 2001:8002 # authoring
         - 1997:8002 # account
         - 1984:8002 # communications
         - 2002:8002 # discussions
         - 1994:8002 # gradebook
         - 1996:8002 # learner-dashboard
         - 2000:8002 # learning
         - 1993:8002 # ora-grading
         - 1995:8002 # profile
