# Tutor provides the `tutor MODE do JOB ...` CLI as a consistent way to execute jobs
# across the dev, local, and k8s modes. To support jobs in the docker compose modes
# (dev and local), we must define a `-job` variant service in which jobs could be run.

# When `tutor local do JOB ...` is invoked, we `docker compose run` each of JOB's
# tasks against the appropriate `-job` services, as defined here.
# When `tutor dev do JOB ...` is invoked, we do the same, but also include any
# compose overrides in ../dev/docker-compose.jobs.yml.

# Note that these services will all be `run` rather than `start`ed and `exec`ed.
# This is because jobs are often used for initialization tasks, which may need to
# happen before the service can be successfully `start`ed.

services:

    mysql-job:
      image: docker.io/mysql:8.4.0
      depends_on: ["mysql"]

    lms-job:
      image: 466538543953.dkr.ecr.eu-central-1.amazonaws.com/phd-experiment-6888bd00add5eb8ac6bb3199:v20.0.0-20250805-pfxsgwaj
      environment:
        SERVICE_VARIANT: lms
        DJANGO_SETTINGS_MODULE: lms.envs.tutor.production
      volumes:
        - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
        - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
        - ../apps/openedx/config:/openedx/config:ro
      depends_on: ["mysql", "mongodb", "meilisearch"]

    cms-job:
      image: 466538543953.dkr.ecr.eu-central-1.amazonaws.com/phd-experiment-6888bd00add5eb8ac6bb3199:v20.0.0-20250805-pfxsgwaj
      environment:
        SERVICE_VARIANT: cms
        DJANGO_SETTINGS_MODULE: cms.envs.tutor.production
      volumes:
        - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
        - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
        - ../apps/openedx/config:/openedx/config:ro
      depends_on: ["mysql", "mongodb", "meilisearch", "redis"]

    aspects-job:
      user: root
      image: edunext/aspects:2.3.1
      environment:
        VENV_DIR: /opt/venv
        ASPECTS_EVENT_SINK_DATABASE: event_sink
        ASPECTS_XAPI_DATABASE: xapi
        CLICKHOUSE_CLUSTER_NAME: ""
        DBT_STATE: /app/aspects-dbt/state
        ASPECTS_DATA_TTL_EXPRESSION: "toDateTime(emission_time) + INTERVAL 1 YEAR"
        DBT_PROFILE_TARGET_DATABASE: "reporting"
        DBT_PROFILES_DIR: /app/aspects/dbt/
        DBT_BRANCH: "v4.0.3"
        DBT_REPOSITORY: "https://github.com/openedx/aspects-dbt"
        DBT_SSH_KEY: ""
      volumes:
        - ../../env/plugins/aspects/apps/aspects:/app/aspects
        - ../../env/plugins/aspects/apps/aspects/scripts/:/app/aspects/scripts:ro
      
      depends_on:
        - clickhouse
      
    clickhouse-job:
        image: clickhouse/clickhouse-server:25.3
        depends_on:
            - clickhouse
        


    superset-job:
      image: edunext/aspects-superset:2.3.1
      user: root
      volumes:
        - ../../env/plugins/aspects/apps/superset/docker:/app/docker
        - ../../env/plugins/aspects/apps/superset/pythonpath:/app/pythonpath
        - ../../env/plugins/aspects/apps/superset/security:/app/security
        - ../../env/plugins/aspects/apps/superset/superset_home:/app/superset_home
        - ../../env/plugins/aspects/apps/superset/scripts:/app/scripts
        - ../../env/plugins/aspects/build/aspects-superset/openedx-assets:/app/openedx-assets        
      restart: unless-stopped
      environment:
        DATABASE_DIALECT: mysql
        DATABASE_HOST: mysql
        DATABASE_PORT: 3306
        DATABASE_DB: superset
        DATABASE_PASSWORD: 83VDXRV5RAQJ7bk4Sg41Mz7q
        DATABASE_USER: superset
        OAUTH2_CLIENT_SECRET: 4FYoh0RsE3PA9qvT
        SECRET_KEY: 6UDIsoIHFGwIqonQsp6Bl5ZC
        PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_PASSWORD: 
        SUPERSET_HOST: superset.www.myopenedx.com
        SUPERSET_PORT: 8088
        OAUTH2_ACCESS_TOKEN_PATH: "/oauth2/access_token/"
        OAUTH2_AUTHORIZE_PATH: "/oauth2/authorize/"
        OPENEDX_LMS_ROOT_URL: "http://www.myopenedx.com"
        OAUTH2_CLIENT_ID: 9i7ptkJ4MCbSQV9r
      depends_on:
        - mysql
        - redis
