services:

  # Set bind-mounted folder ownership
  permissions:
    image: 466538543953.dkr.ecr.eu-central-1.amazonaws.comoverhangio/openedx-permissions:v20.0.0
    restart: on-failure
    entrypoint: []
    command: ["sh", "/usr/local/bin/setowners.sh"]
    environment:
      OPENEDX_USER_ID: "1000"
    volumes:
      # Command script
      - ../apps/permissions/setowners.sh:/usr/local/bin/setowners.sh:ro
      # Bind-mounted volumes to set ownership
      - ../../data/lms:/mounts/lms
      - ../../data/cms:/mounts/cms
      - ../../data/openedx-media:/mounts/openedx
      - ../../data/openedx-media-private:/mounts/openedx-private
      - ../../data/mongodb:/mounts/mongodb
      - ../../data/mysql:/mounts/mysql
      - ../../data/meilisearch:/mounts/meilisearch
      - ../../data/redis:/mounts/redis
      - ../../data/clickhouse:/mounts/clickhouse/

  ############# External services

  mongodb:
    image: docker.io/mongo:7.0.7
    # Use WiredTiger in all environments, just like at edx.org
    command: mongod --storageEngine wiredTiger
    restart: unless-stopped
    user: "999:999"
    volumes:
      - ../../data/mongodb:/data/db
    depends_on:
      - permissions

  mysql:
    image: docker.io/mysql:8.4.0
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --binlog-expire-logs-seconds=259200
      --mysql-native-password=ON
    restart: unless-stopped
    user: "999:999"
    volumes:
      - ../../data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "usMgJmj1"

  meilisearch:
    image: docker.io/getmeili/meilisearch:v1.8.4
    environment:
      MEILI_MASTER_KEY: "OWGGkvUclXbWTQMqbWpMQf9j"
    volumes:
      - ../../data/meilisearch:/meili_data
    restart: unless-stopped
    user: "1000:1000"
    depends_on:
      - permissions

  redis:
    image: docker.io/redis:7.2.4
    working_dir: /openedx/redis/data
    user: "1000:1000"
    volumes:
      - ../apps/redis/redis.conf:/openedx/redis/config/redis.conf:ro
      - ../../data/redis:/openedx/redis/data
    command: redis-server /openedx/redis/config/redis.conf
    restart: unless-stopped
    depends_on:
      - permissions

  smtp:
    image: docker.io/devture/exim-relay:4.96-r1-0
    restart: unless-stopped
    user: "100:101"
    environment:
      HOSTNAME: "www.myopenedx.com"

  ############# LMS and CMS

  lms:
    image: 466538543953.dkr.ecr.eu-central-1.amazonaws.com/phd-experiment-6888bd00add5eb8ac6bb3199:v20.0.0-20250805-pfxsgwaj
    environment:
      SERVICE_VARIANT: lms
      DJANGO_SETTINGS_MODULE: lms.envs.tutor.production
      UWSGI_WORKERS: 2
    restart: unless-stopped
    volumes:
      - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
      - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
      - ../apps/openedx/config:/openedx/config:ro
      - ../apps/openedx/uwsgi.ini:/openedx/uwsgi.ini:ro
      - ../../data/lms:/openedx/data
      - ../../data/openedx-media:/openedx/media
      - ../../data/openedx-media-private:/openedx/media-private
    depends_on:
      - permissions
      - mysql
      - meilisearch
      - mongodb
      - redis
      - smtp
      

  cms:
    image: 466538543953.dkr.ecr.eu-central-1.amazonaws.com/phd-experiment-6888bd00add5eb8ac6bb3199:v20.0.0-20250805-pfxsgwaj
    environment:
      SERVICE_VARIANT: cms
      DJANGO_SETTINGS_MODULE: cms.envs.tutor.production
      UWSGI_WORKERS: 2
    restart: unless-stopped
    volumes:
      - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
      - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
      - ../apps/openedx/config:/openedx/config:ro
      - ../apps/openedx/uwsgi.ini:/openedx/uwsgi.ini:ro
      - ../../data/cms:/openedx/data
      - ../../data/openedx-media:/openedx/media
      - ../../data/openedx-media-private:/openedx/media-private
    depends_on:
      - permissions
      - lms
      - mysql
      - meilisearch
      - mongodb
      - redis
      - smtp
      

  
  clickhouse:
      image: clickhouse/clickhouse-server:25.3
      restart: unless-stopped
      environment:
          CLICKHOUSE_DB: "xapi"
          CLICKHOUSE_USER: "ch_admin"
          CLICKHOUSE_PASSWORD: "WCCxAm9AYpkR2j2NjNDJK6c0"
          CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      ports:
          - 8123:8123
          - 9006:9000
      ulimits:
          nofile:
              soft: 262144
              hard: 262144
      volumes:
          - ../../data/clickhouse:/var/lib/clickhouse/
          - ../../env/plugins/aspects/apps/clickhouse/config:/etc/clickhouse-server/config.d/
          - ../../env/plugins/aspects/apps/clickhouse/users:/etc/clickhouse-server/users.d/



  ralph:
      image: fundocker/ralph:4.1.0
      restart: unless-stopped
      depends_on:
        - clickhouse
      env_file:
        - ../../env/plugins/aspects/apps/ralph/config/env
      ports:
        - "8100:8100"
      command:
        - "uvicorn"
        - "ralph.api:app"
        - "--proxy-headers"
        - "--log-config"
        - "/etc/ralph/logging.yaml"
        - "--port"
        - "8100"
        - "--host"
        - "0.0.0.0"
      volumes:
        - ../../env/plugins/aspects/apps/ralph/config/ralph_auth/:/app/.ralph
        - ../../env/plugins/aspects/apps/ralph/config/logging.yaml:/etc/ralph/logging.yaml:ro



  superset:
    image: edunext/aspects-superset:2.3.1
    user: root
    volumes:
      - ../../env/plugins/aspects/apps/superset/docker:/app/docker
      - ../../env/plugins/aspects/apps/superset/pythonpath:/app/pythonpath
      - ../../env/plugins/aspects/apps/superset/security:/app/security
      - ../../env/plugins/aspects/apps/superset/superset_home:/app/superset_home
      - ../../env/plugins/aspects/apps/superset/scripts:/app/scripts
      - ../../env/plugins/aspects/build/aspects-superset/openedx-assets:/app/openedx-assets        
    restart: unless-stopped
    environment:
      DATABASE_DIALECT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_DB: superset
      DATABASE_PASSWORD: 83VDXRV5RAQJ7bk4Sg41Mz7q
      DATABASE_USER: superset
      OAUTH2_CLIENT_SECRET: 4FYoh0RsE3PA9qvT
      SECRET_KEY: 6UDIsoIHFGwIqonQsp6Bl5ZC
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 
      SUPERSET_HOST: superset.www.myopenedx.com
      SUPERSET_PORT: 8088
      OAUTH2_ACCESS_TOKEN_PATH: "/oauth2/access_token/"
      OAUTH2_AUTHORIZE_PATH: "/oauth2/authorize/"
      OPENEDX_LMS_ROOT_URL: "http://www.myopenedx.com"
      OAUTH2_CLIENT_ID: 9i7ptkJ4MCbSQV9r
      SUPERSET_ENV: production
    command: ["bash", "/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    ports:
      - 8088:8088
    depends_on:
      - mysql
      - redis

  superset-worker:
    image: edunext/aspects-superset:2.3.1
    user: root
    volumes:
      - ../../env/plugins/aspects/apps/superset/docker:/app/docker
      - ../../env/plugins/aspects/apps/superset/pythonpath:/app/pythonpath
      - ../../env/plugins/aspects/apps/superset/security:/app/security
      - ../../env/plugins/aspects/apps/superset/superset_home:/app/superset_home
      - ../../env/plugins/aspects/apps/superset/scripts:/app/scripts
      - ../../env/plugins/aspects/build/aspects-superset/openedx-assets:/app/openedx-assets        
    restart: unless-stopped
    environment:
      DATABASE_DIALECT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_DB: superset
      DATABASE_PASSWORD: 83VDXRV5RAQJ7bk4Sg41Mz7q
      DATABASE_USER: superset
      OAUTH2_CLIENT_SECRET: 4FYoh0RsE3PA9qvT
      SECRET_KEY: 6UDIsoIHFGwIqonQsp6Bl5ZC
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 
      SUPERSET_HOST: superset.www.myopenedx.com
      SUPERSET_PORT: 8088
      OAUTH2_ACCESS_TOKEN_PATH: "/oauth2/access_token/"
      OAUTH2_AUTHORIZE_PATH: "/oauth2/authorize/"
      OPENEDX_LMS_ROOT_URL: "http://www.myopenedx.com"
      OAUTH2_CLIENT_ID: 9i7ptkJ4MCbSQV9r
      SUPERSET_ENV: production
    command: ["bash", "/app/docker/docker-bootstrap.sh", "worker"]
    healthcheck:
      test: ["CMD-SHELL", "celery inspect ping -A superset.tasks.celery_app:app -d celery@$$HOSTNAME"]
    depends_on:
      - mysql
      - redis

  superset-worker-beat:
    image: edunext/aspects-superset:2.3.1
    user: root
    volumes:
      - ../../env/plugins/aspects/apps/superset/docker:/app/docker
      - ../../env/plugins/aspects/apps/superset/pythonpath:/app/pythonpath
      - ../../env/plugins/aspects/apps/superset/security:/app/security
      - ../../env/plugins/aspects/apps/superset/superset_home:/app/superset_home
      - ../../env/plugins/aspects/apps/superset/scripts:/app/scripts
      - ../../env/plugins/aspects/build/aspects-superset/openedx-assets:/app/openedx-assets        
    restart: unless-stopped
    environment:
      DATABASE_DIALECT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_DB: superset
      DATABASE_PASSWORD: 83VDXRV5RAQJ7bk4Sg41Mz7q
      DATABASE_USER: superset
      OAUTH2_CLIENT_SECRET: 4FYoh0RsE3PA9qvT
      SECRET_KEY: 6UDIsoIHFGwIqonQsp6Bl5ZC
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 
      SUPERSET_HOST: superset.www.myopenedx.com
      SUPERSET_PORT: 8088
      OAUTH2_ACCESS_TOKEN_PATH: "/oauth2/access_token/"
      OAUTH2_AUTHORIZE_PATH: "/oauth2/authorize/"
      OPENEDX_LMS_ROOT_URL: "http://www.myopenedx.com"
      OAUTH2_CLIENT_ID: 9i7ptkJ4MCbSQV9r
      SUPERSET_ENV: production
    command: ["bash", "/app/docker/docker-bootstrap.sh", "beat"]
    healthcheck:
      disable: true
    depends_on:
      - mysql
      - redis







  # MFE
  mfe:
      image: 466538543953.dkr.ecr.eu-central-1.amazonaws.com/phd-experiment-6888bd00add5eb8ac6bb3199:teak-demo-mfe
      restart: unless-stopped
      volumes:
          - ../plugins/mfe/apps/mfe/Caddyfile:/etc/caddy/Caddyfile:ro
      depends_on:
          - lms