x-openedx-job-service:
  &openedx-job-service
  image: 466538543953.dkr.ecr.eu-central-1.amazonaws.com/phd-experiment-6888bd00add5eb8ac6bb3199:mfe-demo-dev
  build:
    context: ../build/openedx/
    target: development
    args:
      # Note that we never build the openedx-dev image with root user ID, as it would simply fail.
      APP_USER_ID: "1001"
  volumes:
    # Settings & config
    - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
    - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
    - ../apps/openedx/config:/openedx/config:ro
    # theme files
    - ../build/openedx/themes:/openedx/themes

services:

  lms-job:
    <<: *openedx-job-service
    environment:
      DJANGO_SETTINGS_MODULE: lms.envs.tutor.development


  cms-job:
    <<: *openedx-job-service
    environment:
      DJANGO_SETTINGS_MODULE: cms.envs.tutor.development

  