from alembic import op
import clickhouse_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0041'
down_revision = '0040'
branch_labels = None
depends_on = None
on_cluster = " ON CLUSTER '' " if "" else ""
engine = "ReplicatedMergeTree" if "" else "MergeTree"



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    op.execute(
        "DROP DICTIONARY IF EXISTS reporting.dim_most_recent_course_tags"
        f"{on_cluster}"
    )
    op.execute(
        "DROP DICTIONARY IF EXISTS event_sink.dim_course_names"
        f"{on_cluster}"
    )