---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/namespace.yml
- k8s/deployments.yml
- k8s/jobs.yml
- k8s/services.yml
- k8s/volumes.yml
- plugins/drydock/k8s/multipurpose-jobs.yml
- plugins/drydock/k8s/pdb/openedx-pdb.yml
- plugins/drydock/k8s/ingress/issuer.yml
- plugins/drydock/k8s/ingress/lms.yml
- plugins/drydock/k8s/ingress/cms.yml
- plugins/drydock/k8s/ingress/mfe.yml
- plugins/drydock/k8s/ingress/meilisearch.yml
- plugins/drydock/k8s/ingress/notes.yml
- plugins/drydock/k8s/ingress/extra-hosts.yml
- plugins/drydock/k8s/ingress/static-cache.yml



# namespace to deploy all Resources to
namespace: openedx

# annotations added to all Resources
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/commonannotations/
commonAnnotations:
  app.kubernetes.io/version: v20.0.0

# labels (and label selectors) added to all Resources
# https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/commonlabels/
commonLabels:
  app.kubernetes.io/instance: openedx-qA0yRGJm19EeQRoxlza9GLLU
  app.kubernetes.io/part-of: openedx
  app.kubernetes.io/managed-by: tutor
  

configMapGenerator:
- name: caddy-config
  files:
  - apps/caddy/Caddyfile
  options:
    labels:
        app.kubernetes.io/name: caddy
- name: openedx-settings-lms
  files:
  - apps/openedx/settings/lms/__init__.py
  - apps/openedx/settings/lms/development.py
  - apps/openedx/settings/lms/production.py
  - apps/openedx/settings/lms/test.py
  options:
    labels:
        app.kubernetes.io/name: openedx
- name: openedx-settings-cms
  files:
  - apps/openedx/settings/cms/__init__.py
  - apps/openedx/settings/cms/development.py
  - apps/openedx/settings/cms/production.py
  - apps/openedx/settings/cms/test.py
  options:
    labels:
        app.kubernetes.io/name: openedx
- name: openedx-config
  files:
  - apps/openedx/config/cms.env.yml
  - apps/openedx/config/lms.env.yml
  options:
    labels:
        app.kubernetes.io/name: openedx
- name: openedx-uwsgi-config
  files:
  - apps/openedx/uwsgi.ini
  options:
    labels:
        app.kubernetes.io/name: openedx
- name: redis-config
  files:
  - apps/redis/redis.conf
  options:
    labels:
        app.kubernetes.io/name: redis
- name: aspects-scripts
  files:
  - plugins/aspects/apps/aspects/scripts/alembic.sh
  - plugins/aspects/apps/aspects/scripts/bootstrap.sh
  - plugins/aspects/apps/aspects/scripts/clickhouse-demo-xapi-data.sh
  - plugins/aspects/apps/aspects/scripts/dbt.sh
  - plugins/aspects/apps/aspects/scripts/docs.sh
  - plugins/aspects/apps/aspects/scripts/insert_data.py
  - plugins/aspects/apps/aspects/scripts/xapi-db-load-config.yaml
  options:
    labels:
        app.kubernetes.io/name: aspects
- name: aspects-dbt
  files:
  - plugins/aspects/apps/aspects/dbt/profiles.yml
  options:
    labels:
        app.kubernetes.io/name: aspects

- name: aspects-migrations
  files:
  - plugins/aspects/apps/aspects/migrations/alembic.ini
  options:
    labels:
        app.kubernetes.io/name: aspects

- name: aspects-migrations-alembic
  files:
  - plugins/aspects/apps/aspects/migrations/alembic/env.py
  - plugins/aspects/apps/aspects/migrations/alembic/script.py.mako
  options:
    labels:
        app.kubernetes.io/name: aspects

- name: aspects-migrations-alembic-versions
  files:
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0001_get_org_from_course_url.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0002_raw_xapi_table.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0007_event_sink.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0008_vector.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0010_course_dictionaries.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0011_vector_replacingmergetree_xapi_raw.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0014_add_course_names_fields.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0015_add_course_key_blocks.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0016_event_sink_user_profile.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0017_add_graded_course_block_names.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0020_get_org_from_course_url.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0023_extend_display_names.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0026_event_sink_external_id.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0027_partition_event_sink_user_profile.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0028_user_pii.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0029_drop_json_column.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0030_rename_vector_json_column.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0031_add_email_user_profile.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0032_partition_tables_by_year_and_month.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0033_ccx_function.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0034_load_test_table.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0035_migrate_dictionaries.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0036_course_enrollments.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0037_remove_most_recent_course_blocks.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0038_aspects_data.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0039_event_sink_tag_taxonomy.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0040_user_profile_username.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/0041_drop_course_dictionaries.py
  - plugins/aspects/apps/aspects/migrations/alembic/versions/__init__.py
  options:
    labels:
        app.kubernetes.io/name: aspects


- name: clickhouse-user-settings
  files:
    - plugins/aspects/apps/clickhouse/users/user_config.xml
  options:
    labels:
        app.kubernetes.io/name: clickhouse
- name: clickhouse-server-settings
  files:
    - plugins/aspects/apps/clickhouse/config/server_config.xml
  options:
    labels:
        app.kubernetes.io/name: clickhouse



- name: ralph-settings
  files:
    - plugins/aspects/apps/ralph/config/ralph_auth/auth.json
  options:
    labels:
        app.kubernetes.io/name: ralph

- name: ralph-logging
  files:
    - plugins/aspects/apps/ralph/config/logging.yaml
  options:
    labels:
        app.kubernetes.io/name: ralph



- name: superset-docker
  files:
    - plugins/aspects/apps/superset/docker/docker-bootstrap.sh
    - plugins/aspects/apps/superset/docker/requirements-local.txt
  options:
    labels:
        app.kubernetes.io/name: superset

- name: superset-pythonpath
  files:
  - plugins/aspects/apps/superset/pythonpath/aspects_asset_list.yaml
  - plugins/aspects/apps/superset/pythonpath/assets.yaml
  - plugins/aspects/apps/superset/pythonpath/collect_dbt_lineage.py
  - plugins/aspects/apps/superset/pythonpath/create_assets.py
  - plugins/aspects/apps/superset/pythonpath/openedx/create_assets_utils.py
  - plugins/aspects/apps/superset/pythonpath/openedx/create_row_level_security.py
  - plugins/aspects/apps/superset/pythonpath/openedx/delete_assets.py
  - plugins/aspects/apps/superset/pythonpath/openedx/localization.py
  - plugins/aspects/apps/superset/pythonpath/openedx_jinja_filters.py
  - plugins/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
  - plugins/aspects/apps/superset/pythonpath/performance_metrics.py
  - plugins/aspects/apps/superset/pythonpath/superset_config.py
  - plugins/aspects/apps/superset/pythonpath/superset_config_docker.py
  options:
    labels:
        app.kubernetes.io/name: superset

- name: superset-pythonpath-openedx
  files:
  - plugins/aspects/apps/superset/pythonpath/openedx/create_assets_utils.py
  - plugins/aspects/apps/superset/pythonpath/openedx/create_row_level_security.py
  - plugins/aspects/apps/superset/pythonpath/openedx/delete_assets.py
  - plugins/aspects/apps/superset/pythonpath/openedx/localization.py
  options:
    labels:
        app.kubernetes.io/name: superset

- name: superset-security
  files:
    - plugins/aspects/apps/superset/security/roles.json
  options:
    labels:
        app.kubernetes.io/name: superset

- name: superset-scripts
  files:
  - plugins/aspects/apps/superset/scripts/import-assets.sh
  options:
    labels:
        app.kubernetes.io/name: superset



- name: mfe-caddy-config
  files:
    - plugins/mfe/apps/mfe/Caddyfile
  options:
    labels:
        app.kubernetes.io/name: mfe

patchesStrategicMerge:
- plugins/mfe_extensions/k8s/mfe-deployment-overrides.yml

patches:
- path: plugins/drydock/k8s/lifecycle/lms.yml
- path: plugins/drydock/k8s/lifecycle/cms.yml
- target:
    kind: Job
    labelSelector: app.kubernetes.io/component=job
  path: plugins/drydock/k8s/patches/tutor-jobs.yml
- target:
    kind: HorizontalPodAutoscaler
  path: plugins/drydock/k8s/patches/hpa-sync-wave.yml
- target:
    kind: Deployment
    name: 'lms|cms|forum|lms-worker|cms-worker|superset|superset-worker|superset-celery-beat'
  path: plugins/drydock/k8s/patches/post-init-deployments-sync-wave.yml