---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/namespace.yml
- k8s/deployments.yml
- k8s/jobs.yml
- k8s/services.yml
- k8s/volumes.yml
- plugins/drydock/k8s/multipurpose-jobs.yml
- plugins/drydock/k8s/pdb/openedx-pdb.yml
- plugins/drydock/k8s/jobs.yml
- plugins/drydock/k8s/ingress/issuer.yml
- plugins/drydock/k8s/ingress/lms.yml
- plugins/drydock/k8s/ingress/cms.yml
- plugins/drydock/k8s/ingress/mfe.yml
- plugins/drydock/k8s/ingress/meilisearch.yml
- plugins/drydock/k8s/ingress/notes.yml
- plugins/drydock/k8s/ingress/extra-hosts.yml
- plugins/drydock/k8s/ingress/static-cache.yml

- plugins/drydock/k8s/secrets/image-pull-secret.yml


# namespace to deploy all Resources to
namespace: openedx

# annotations added to all Resources
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/commonannotations/
commonAnnotations:
  app.kubernetes.io/version: v20.0.0

# labels (and label selectors) added to all Resources
# https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/commonlabels/
commonLabels:
  app.kubernetes.io/instance: openedx-zFEyHDhICmqTOXunlClRhDFW
  app.kubernetes.io/part-of: openedx
  app.kubernetes.io/managed-by: tutor
  

configMapGenerator:
- name: caddy-config
  files:
  - apps/caddy/Caddyfile
  options:
    labels:
        app.kubernetes.io/name: caddy
- name: openedx-settings-lms
  files:
  - apps/openedx/settings/lms/__init__.py
  - apps/openedx/settings/lms/development.py
  - apps/openedx/settings/lms/production.py
  - apps/openedx/settings/lms/test.py
  options:
    labels:
        app.kubernetes.io/name: openedx
- name: openedx-settings-cms
  files:
  - apps/openedx/settings/cms/__init__.py
  - apps/openedx/settings/cms/development.py
  - apps/openedx/settings/cms/production.py
  - apps/openedx/settings/cms/test.py
  options:
    labels:
        app.kubernetes.io/name: openedx
- name: openedx-config
  files:
  - apps/openedx/config/cms.env.yml
  - apps/openedx/config/lms.env.yml
  options:
    labels:
        app.kubernetes.io/name: openedx
- name: openedx-uwsgi-config
  files:
  - apps/openedx/uwsgi.ini
  options:
    labels:
        app.kubernetes.io/name: openedx
- name: redis-config
  files:
  - apps/redis/redis.conf
  options:
    labels:
        app.kubernetes.io/name: redis
- name: mfe-caddy-config
  files:
    - plugins/mfe/apps/mfe/Caddyfile
  options:
    labels:
        app.kubernetes.io/name: mfe

patchesStrategicMerge:
- plugins/mfe_extensions/k8s/mfe-deployment-overrides.yml

patches:
- path: plugins/drydock/k8s/lifecycle/lms.yml
- path: plugins/drydock/k8s/lifecycle/cms.yml
- target:
    kind: Deployment
  path: plugins/drydock/k8s/patches/add-image-pull-secret.yml
- target:
    kind: Job
  path: plugins/drydock/k8s/patches/add-image-pull-secret.yml
- target:
    kind: CronJob
  path: plugins/drydock/k8s/patches/add-image-pull-secret-cronjob.yml
- target:
    kind: Job
    labelSelector: app.kubernetes.io/component=job
  path: plugins/drydock/k8s/patches/tutor-jobs.yml
- target:
    kind: HorizontalPodAutoscaler
  path: plugins/drydock/k8s/patches/hpa-sync-wave.yml
- target:
    kind: Deployment
    name: 'lms|cms|forum|lms-worker|cms-worker|superset|superset-worker|superset-celery-beat'
  path: plugins/drydock/k8s/patches/post-init-deployments-sync-wave.yml