SITE_NAME: "studio.teak-demo.phd.opencraft.hosting"
BOOK_URL: ""
LOG_DIR: "/openedx/data/logs"
LOGGING_ENV: "sandbox"
OAUTH_OIDC_ISSUER: "https://teak-demo.phd.opencraft.hosting/oauth2"
PLATFORM_NAME: "Picasso Harmony Drydock Experimentation"
FEATURES:
  
  
  CERTIFICATES_HTML_VIEW: true
  PREVIEW_LMS_BASE: "preview.teak-demo.phd.opencraft.hosting"
  ENABLE_CSMH_EXTENDED: false
  ENABLE_LEARNER_RECORDS: false
  ENABLE_LIBRARY_INDEX: true
  MILESTONES_APP: true
  ENABLE_PREREQUISITE_COURSES: true
LMS_ROOT_URL: "https://teak-demo.phd.opencraft.hosting"
CMS_ROOT_URL: "https://studio.teak-demo.phd.opencraft.hosting"
CMS_BASE: "studio.teak-demo.phd.opencraft.hosting"
LMS_BASE: "teak-demo.phd.opencraft.hosting"
CONTACT_EMAIL: "contact@teak-demo.phd.opencraft.hosting"
CELERY_BROKER_TRANSPORT: "redis"
CELERY_BROKER_HOSTNAME: "redis:6379"
CELERY_BROKER_VHOST: "0"
CELERY_BROKER_USER: ""
CELERY_BROKER_PASSWORD: ""
ALTERNATE_WORKER_QUEUES: "lms"
ENABLE_COMPREHENSIVE_THEMING: true
EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST: "smtp"
EMAIL_PORT: 8025
EMAIL_USE_TLS: false
HTTPS: "on"
LANGUAGE_CODE: "en"
SESSION_COOKIE_DOMAIN: "studio.teak-demo.phd.opencraft.hosting"

DEFAULT_SITE_THEME: "bragi"


SECRET_KEY: "hg3b7OklRLkOYp8HuRw2c9i7"
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
DOC_STORE_CONFIG: null
XQUEUE_INTERFACE:
  django_auth: null
  url: null
DATABASES:
  default:
    ENGINE: "django.db.backends.mysql"
    HOST: "mysql"
    PORT: 3306
    NAME: "openedx"
    USER: "openedx"
    PASSWORD: "E9yp0EiB"
    ATOMIC_REQUESTS: true
    OPTIONS:
      init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
      charset: "utf8mb4"
EMAIL_HOST_USER: ""
EMAIL_HOST_PASSWORD: ""
