SITE_NAME: "www.myopenedx.com"
BOOK_URL: ""
LOG_DIR: "/openedx/data/logs"
LOGGING_ENV: "sandbox"
OAUTH_OIDC_ISSUER: "http://www.myopenedx.com/oauth2"
PLATFORM_NAME: "My Open edX"
FEATURES:
  
  
  CERTIFICATES_HTML_VIEW: true
  PREVIEW_LMS_BASE: "preview.www.myopenedx.com"
  ENABLE_CSMH_EXTENDED: false
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
  ENABLE_GRADE_DOWNLOADS: true
  ENABLE_LEARNER_RECORDS: false
  ENABLE_MOBILE_REST_API: true
  ENABLE_OAUTH2_PROVIDER: true
  ENABLE_PREREQUISITE_COURSES: true
  ENABLE_THIRD_PARTY_AUTH: true
  MILESTONES_APP: true
LMS_ROOT_URL: "http://www.myopenedx.com"
CMS_ROOT_URL: "http://studio.www.myopenedx.com"
CMS_BASE: "studio.www.myopenedx.com"
LMS_BASE: "www.myopenedx.com"
CONTACT_EMAIL: "contact@www.myopenedx.com"
CELERY_BROKER_TRANSPORT: "redis"
CELERY_BROKER_HOSTNAME: "redis:6379"
CELERY_BROKER_VHOST: "0"
CELERY_BROKER_USER: ""
CELERY_BROKER_PASSWORD: ""
ALTERNATE_WORKER_QUEUES: "cms"
ENABLE_COMPREHENSIVE_THEMING: true
EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST: "smtp"
EMAIL_PORT: 8025
EMAIL_USE_TLS: false
ACE_ROUTING_KEY: "edx.lms.core.default"
HTTPS: "off"
LANGUAGE_CODE: "en"
SESSION_COOKIE_DOMAIN: "www.myopenedx.com"

DEFAULT_SITE_THEME: "bragi"


SECRET_KEY: "tJgTu8nPQWQ8tcjhKi33gP1J"
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
DOC_STORE_CONFIG: null
XQUEUE_INTERFACE:
  django_auth: null
  url: null
DATABASES:
  default:
    ENGINE: "django.db.backends.mysql"
    HOST: "mysql"
    PORT: 3306
    NAME: "openedx"
    USER: "openedx"
    PASSWORD: "ij2iBXCG"
    ATOMIC_REQUESTS: true
    OPTIONS:
      init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
      charset: "utf8mb4"
EMAIL_HOST_USER: ""
EMAIL_HOST_PASSWORD: ""
